sudo: false
language: node_js
node_js:
  - '10'
branches:
  only:
    - travis
cache:
  directories:
    - node_modules
    - server/node_modules
    - client/node_modules
before_install:
  - npm run update-all
install:
  - npm run install-all
script:
  - npm run validate
env:
  matrix:
    secure: NATcVTTGEJzL7XaCubS9NjEmrWHPIp+HlJ0sy4+0Z2I1KSgYqFCEiI2sD9I6at9R5k/SgdsjLM9NuWUCcSb5wrK/I88p7xN45v2MI2O5wbfPR+m8l5hGZEyr20dsRWxStSrFmjiha5gh2wmh6VtPKzrp/yx+NIJmiqmeT/sCWehG/h1eNPHeswmtcERNUN6eByvziiEOumFC9Ob24K1npJ8PKrQiD2IpaiWCSNRMZfeDy4vCUl0opJB5dQCHuOt5JWd8FAce0SUGQsrPjs3NTQ8t404Ez+A6CUgfNXZCcJ7NjM9tT1MBl1CvooWbJ0jnPEEh35TJ/FouDP8UJ0J6gdWVOBcGwVp3/aY6rIBOFc7I0MsdcsuyH3/C+LYkixqPuGwqK/NjW++WmONdpljnvGnYQ9KsWpwfe80Xc3OrF/LS8aBtvGGko0efdyUKZvtWoh/zPYb79tye8MmA0K7p9NcvFP9SGx+bq0NpFkoOGQtt+gfs0rBSXq5iZssTgadICfKGPg/JRl5JAA+h05C6bXK9ui66k2dPIZDGcWuyp+v056t4piEQ1xh05KqD8aEogRK+Uk3pegikFAw6JVK3UbpkC6z0lF6Ndv1OM1uOGYOAmF57L85c/R5bYTnDSY7wGETZtHWPlTzEAUt+/Z8zEAg/dmNiZ0OPKkHGFN41EEU=
