sudo: false
language: node_js
node_js:
  - '10'
branches:
  only:
    - travis
cache:
  directories:
    - node_modules
    - server/node_modules
    - client/node_modules
before_install:
  - npm run update-all
install:
  - npm run install-all
script:
  - npm run validate
env:
  global:
    - NODE_ENV=travis
    - DB_DB=test
    - KEYGRIP_SECRETS="secret1 test2 aha3"
    - MIGRATION_PASS="undefined"
    - SENDGRID="NotUsed"
    - secure: oYjKbwk/BR4Wm3RhgH2cjtib8jeHTalcudiDc+8fWAdZNckkCVJu4sHk1T0SAZZCh4RoAwfzegqWswEQVcLo7c3LYq2k6AEWf4Ze64tjjEdTbbJ37YiZVLumHsTXXTTbkHYKTE8atHYLthuRaOfcQ6Blr4zntIw/oycv8D+cmW1hcCzvKK2JZNxLTdsmOBxBOxhWGPga6tJAgfCNgiqZJDcljfoEb2K2+tmkpJF5mO/mfKBB/P9fTX+WSLA8e3ha3h1ZIPcNWQgTvfqDgOhzPPLXASb3Tf3HCW+51TpU1gs0YtNGRGRxUSCI3wpb1jDyEp+oi5EutP9iVioQbzNi71VDpO+Hcc66nHb9G/Lo//ovOtSfB07ibSnzrOmU+M+2qt3Zy6wdzdLYJs//SM2aqurWKMlgYMf/X8D2F5gFas8W9SGD/6O74GLh1sFgW8fvHlkGH5/tfh3Ux5tR+IGS0R7lqHRgTLFxHpbXOdbaPUBWcFCwDV8qO2tScSLphOMZ6357FuWtEmrW8T7bYFe9zjYgXQ0t9pn46UigjzVfBX3MlU6KndBk/rLpGkXXc2k3kgDg00a86twicLXlIVU/1K24yh0AErV3SuNX0IhGouMoXBevZgHRTaubwJze4Tqx3GZPQsC4Re2Wiy1pW2tfSu7R1y118dE3IxdGscfYeQg=
    - secure: Qqut1SMAH7IAUltyGKw6ISPSLW0zg5tjtiNWGdZnROW8tSJmq5+ewmkjZ1Ywl/0DPDXBRf4zaRafv5S5qG1XcX3IAWWYyqvfJxXaVs8aBK5bl0Vs9MsX6FQ3o+qJUCcGxLrIMVbjyOCgZ2/7RTuyP56CU1vJkmaIl05kR3IQCHQotXLFKBCuUMLFKE6FNlrbSlQxNX5KhtZt3FEc06Lt434sDUbfG65PU2CywcfvwlpY8aTd6SLnMUkIwaGY78+uwzDngv5lVnf+sdyRda/Jn7NaURfEHZvdlCM9FS+RZQ+sLrXXp/k62pTI3TeW15SR1k3kYMm19OR7IPXY40DPm98DHHm8s6YJhZGh6ywLsYxOcnMZ636fK8UGHFtrBi5pdQvPCRLiDqr3rTqRO6CXVYoWtERKb8uOsnVZC/VRIpLqhJacqoSDRfqBGbtqbtFvdJxTNXPpCBCcrw70sO0NroKkh8/JDRULHo54ZEZ/qVOsP+HXEBzADp52tIxlgPs9TIEWKpV0VLTO3ZUtF5FqY3qqLKjocmKS0V58bwb1pla9TBOWF9WezXAqZn6QoOuHCluVdn6wL3j6q0KHLJ+xYN/T4MiVEF3w6hihuv5gtAi7c+HEJrgppDpNm/8FEBl66u7AQwmGDSPpBtJ1ahG5CPns+jotWt9U/wUQixlwqr4=
    - secure: EiPXHDqyFjvoil4O1yDwIqcmYpfSN/l6iIus9cqSMyG/2W0l1iox4RQr4TNbug5B2PwZTg6U4FQow6URDkalU8j29QVMLeUFlE2T2MtLa9pE3b+/xap2gPRk6XoI039IJU6x2MozMFTh0kjljDeZDpY1tqZhThyRjOI11fA6trmUH3Do7jBD/u9Kx4xrJnxTlsv6xCzIsB4voGjpil+qbVtuNLMHYdcVjhlJwo7tsBnHEzB87+F8uHJPIXLEMmw1p1f6vEMNFPIkL3HfzW2644jXBk/L2TFj/XhbJWAEPsJ3QjxNNey/CDjiWvjka1P24p8fNr7pUdP9NNWxhvVWgfva7MiqB5IiVJcmx5JppzklnBA1efmaZjE8MUFc8alVNl9fw+Jo9L4SzEs51cgVl+yzMK/rrlaDo4oY3oX3hh7Adva27j38/DBkjEgxkMEM+sjCNhgtr9Ex5PSaa89zWSDFqLi/x7vLiwgmu2Alf8JACddrpBBSGy8QHiFHKL3XxPpHNnUSg6SLOOVhQsD+HIdz7ZyKOX2OpUdtfRZsRR/WbgZt99SUILM2lKjfiAtn5IkhQU+tepw1njINsjRFLICkyYaDPj+hfofCzg6PyGMRitlL5TD7hsYT8/aEF0NPOCqp1/0rC/gQInAkRbvN1H4waAFDiyX1Xc/BHfyueqg=
