sudo: false
language: node_js
node_js:
- '10'
branches:
  only:
  - travis
cache:
  directories:
  - node_modules
  - server/node_modules
  - client/node_modules
before_install:
- npm run update-all
install:
- npm run install-all
script:
- npm run validate
env:
  global:
  - NODE_ENV=travis
  - DB_DB=test
  - KEYGRIP_SECRETS="secret1 test2 aha3"
  - MIGRATION_PASS="undefined"
  - SENDGRID="NotUsed"
  - secure: g7J3PoUI1vw7s+eVO0i7tvxYU3MBZkE7Tp9Aqn4r0lDLII686ilZTY1xT0hGkYOAVkdVI3+SolpSNNa4MDe2z88MjxqMYIgT3mkcyba9xklG9OrDn7W0CuKFGrJf4W/vYhpIEQiUKbL0jb/C/2q0y+IDo7PiAoZEaGvzZV+MJCCBL7PCqgP1cgjelPhZ0vkf4+qjRcdZRNEVGAaK5ktqPh7BirpgXF4rGvwQV8Uo3KbUgVk05gZYMDGWLpEcyzjD5aRmxmlCwpjj5inEC16yEh15xtQmUYtxYAHd7i9MXZE+XesZctxwMy4H/GSH8v7yDvcwsnzU3CCMPLUXjQMxGcpAGiKYEHWRMHc326HBjEYxIu2NcF1whTCBQAihf9oTVKmq0L0v/CyYsG77Mv41iBz2MQS+C/cch33OOR0Bww1gmX6IslTXbNH6tEdRFyN99BJ4hP64VtEnChQ4uTW5lkE5ZguInltQUVIyXowgIOpk+BEOuT42n/vcolqiEyw7JkieKEPx9GMg1T/2H9qVSd7T3pBGjZWZH58dIM/jJn04Vpk+43dg4zivQov0a9fIqSoW1T3+6NNMPXVHnzWmSY1kY4dLfGfU5DlmlLl8mBIPx3WocIW2BWigt6tDC+xwxRaplAO1LCBLW0rDPl0rnS/2h7n5Ea6whuZKLTB7QpE=
  - secure: BMzhdtr8ge68yPAL8IdK1er7TzdmtUmdjM3PvRH+75JOP4eLlYbx2xxYcIAX4W7ujXGDT5y8gUDrt9orfThcaZBzCqSmMXBgG6ZOYlFXwv9RIQm2w5sLPHhZRv3se0EO4AK/+Pl7aoUBxWNJ2Oc3TPECvS30xV9eIPAEF4aFNF2CQGDspIJoGl7D9cxgpRGOIj+UVgFu5i4/TekuCYKu26KhFRHqoqlHNbxGtEAMOCIHchZPAoZeWR1sUfS7v8qfJyNaIjj1njcSfhnvdYE10/JgcMW2zABTC+38ol0gEks7+YN/c3QU1XJ6/ujXGAZnnqJZ0OXvS6ZUC7Fd4zWMmph9b/CBfH5OeIGZfRRsIK2lYAPqR2qHf7+gcUNQdI5fQDPObjPbHevJ1oE9L+HbFKRWBvLPznjoAsk8/rW57nFBUvZFIk4PLnqQ0Nr8SbEHc1h7J/5yE9f6tlVx2EVCsLooxrq7VOoVxWABiN+o4lApNDkrDB7ghBqNukXxkfbhAjK9u8IgTXcumYSeRvMWJ2l6snvqz5zZEyfofdcaaduawc+ov8P9Zzn61HXa4woXJr704bQuzx60JV+mW1jU7RDcM1pu4tIHrF4jK4/FZMHFKb8dlc1MYyLNa6Dltsebsf1yaoIGE8ZpHcWdXA3TYxSJ5xuM4hFU3d0jUk8AqV4=
  - secure: l2uc8nZTtOMCtWRLWMM3387KF2FF+ewsloiYIKSyZlR+7wIs3PZh6xP2ybTzSaI62nUKqN+Ji0MKs3io1ne6N2FjQbamxQ2hx8VT7hgy9KpowPkcW7KkodcXGfZTZe1IVMUOoq8QStAq12s1vdGXJjM6zmO15+HaqPVpZ10hZNa3fCgCYA4f5cU8gXlvZ26sQm9IZXPA0+MjgBM+5J6Nu/sbHV5kKjOWqEqFY6E8I9qsK613UAYaI9ZLQvqlyB86S772ZVy/I1coLExJlHY7SLFVv6Ie4iwQka++qb3fD9Zy1K6YqmxsiZA7N0eWqNoxDmZtB8NvAzPe5mu08co9YewFxE7JvYMFYL6rv7DOunLDCBuJejD9arpuBSOXDCFhF+cH6sZVnnNnwnaIZ5KDV98z8TTZifYTq+3qORaepnqUijKtF7eqiLKT4zuXA9ZXx8gatuq/9LmgvlljV2xLR7A6OX5zqpN01TnACVIkX87q5CaLVSM4Koqnf59KH9j/3SLK2K6tCDb3KWat8xSpF5Eje9AajhY/ZIaw/9YlVF8+hkzFFaR1LdI2MA9KFLJ7LDRKtfW3jRYVkGTnGaKLRBMVrlzV/uigVMCV4IdoQC3npe8PDGWp24CDCurUtHUES9/pj2KxLbMJtA5i2eqUssty8OvohTE0ul6iUXwxSGo=
