sudo: false
language: node_js
node_js:
  - '10'
branches:
  only:
    - travis
cache:
  directories:
    - node_modules
    - server/node_modules
    - client/node_modules
before_install:
  - npm run update-all
install:
  - npm run install-all
script:
  - npm run validate
