sudo: false
language: node_js
node_js:
- '10'
branches:
  only:
  - travis
cache:
  directories:
  - node_modules
  - server/node_modules
  - client/node_modules
before_install:
- npm run update-all
install:
- npm run install-all
script:
- npm run validate
env:
  matrix:
  - NODE_ENV=travis
  - DB_DB=test
  - KEYGRIP_SECRETS="secret1 test2 aha3"
  - MIGRATION_PASS="undefined"
  - SENDGRID="NotUsed"
  - secure: nUGSlufJzTAIytng0OQKmdh/5JMYexViWTRebP1nd2hu1sULTbrwS/kReh6BcpRZ7kt/VUTdm+C9r8jZeLTEkTpQiEfcLogCpgL2CR7wk3hgk8IBptYNSV4mtmcsqwqJ8tnlI/qE/JG8X0+pvG3GdRRzWRUGD4FTDrcS061l8cKojBRyWBfRO7ewe00HhU6t+v8W3psmePJ9HFTqrfB8bWtQKv8/jT0NF3KTDF+9cn8wrUe3dgKlVCuRLPcqEMg0JSFssOyt7lMfRTXN9zCgtuSaj2y8MATAGPpaPNBMVRoSV9PNy4P9K0G1G1rVKeWGxNOts9boYkdaiAjVzN7Z4SW+fcx2JjYSwucAQJSn6aIx5uUoObif0NBpXuLyQ80pLLOzCbQGyCTLWH0IbQhm6Fx8Ry4xuJ+cbPgangFE/hkvAm/gWScPaXX7RErykiymG+pekJn4k5YqrspOLod62sH/7OfrHE/ndLa5O0Rs2fzq+S1UAKId2jpX3YcgkhcgcgQ2WsDwMWkcdfb6CEV3JtV8XjfbWEO+CVCOvyHmxAh7sSwfp0F4RkHDNauy4vuN3D5VbdhN6fRtPlBblPVtJuB3I3gt6zDW0shY+gVyHFJ2JTKj4cRgijbEV3S7+3drzYH+8JGioI7DzJmmcTLl7Y5mrX97skdjtJ8Q2IpQ0Wo=
  - secure: YgoYRONqw0vnrVxeQP9DPaKwjF7fyoNo28VUA3dvILyaRlEB4KMvaTVd4t/4BnFbtFEeFP3pLF9WoRln3Bl3a2qJc25jQsfHXqoZTvUflELlbYCtTUc8FiXeNx56blbZT1AeoNQpj6t6/Fg4HdSwV3tBKuZFsC+tV1Zkm7KTTSUeVdAKDf23+1pE2H7k2aVQyprSmHG5NakdtOWmIDxTbjPDJ8n/4xFgYVl2S016Fen0H3Z3lJEC6J/TIt276Uk61FX6R6EUL5MX0yZMWkaKLobZwnG43WCR2pcp+hfrUSYVT/qLbRC+gzKhRwdVQjPSarm4zUW+NUzS2g45H/s99wrsvr8JScWvN2v8jmHa15Xq7DwUctNF+daqmVY80oPHaJLBFgY6N9E6OQqaWpJn8oughEzMS0Kxrg7nwk6yPh5tBTu+Snn5rvM/SW45SA66/LQZmmmJlAfykR2oWZAbmlIyLJn6NPizoRIKaMoftQ0u+qJFP+O25qjKLvggeiBWIwSx5z07qbel7FUB5+MU/YD+sWwtgITOmkteIrXPDjDHZMIOy/6YdiWA5XecrEiInnGPCGx2aHYVb2giv3erG28IwtPcClLuO9VhBgx8aF0XlyQ59/36KWkCHEK8R678PC3m7Hz84QMG2A2StiX3bizCclu7SlmsbfQf8b5+2nM=
  - secure: EJ8oPw3rJ/sB/VY6dibqWIAEVoHxGSQ+8d66vddZVzaRCFRpJnocK8KCuk7pybOd/eFyBDKmu86ZeVMteCr0VyJTJi8KNP1tXYFgJ7tGCxyDt4dhOOmkRpFrKx3ejL5hhNZzoiwSSzWwog+HPLoEpK+GQhcD3yhJE0Z2o9LuoGlZAYUDPjiLZAh+LummbF99xRUFSc8zZkXejMhnBL4xE1/i2EhrwtoPeTzSFqGJWnQGwLk476FAPYjJJURo9rAJAr4IdwMmEf/URJ0VSksYFsTNouFpU8uwB/d2b+HqD8e5Fxeb5frXyuyrLe5K+Swt8SeeBLNKKGaup4Vcowkf6PpfgZyRyecmhLvYLxV9f9EkB7xEa0RbNDZrscR7L0v5kk/ZUW80VIAg0irBrP/8wY+b99OTUK9CAhLYv4mxCLrWjcYnp4FV8CGyv4e009kGcN/swBK1Iym5c3exgLFg205E3WEKMcNAGScBL8WpOjC/kDjPBYQ6wki897DUBaSfGZvK9PlTyyrzy5noJN/junwULVyjLt4On5v1kAPSEF8guoRKf05aycOVZHPgBPNTkUbI+SCLga3Ap86E1tTKSSzgV/DIFr1xQZG7qlyKsNF49w54zAFsnwxLbSr9zTvTCehcJ6eOpsYuMZYXeNHjenWAibWl2KW8zu3cxitPoOY=
  - secure: EfmJ14AFXV4F08+/4OSTr7hJzwBemd/7DequQV6EdgPO99Qu1YS0ZJbfN7CI3KhUi12JEIbbjw6xit7FVPV9uZ8dWrN3pluIMXlNSSaAWfJxqFSpp/rTbTZF/Jlunva03/OAm6PMS8lEuYtUiYvw5wJ/RP8F5D8e1zDe7o7lLlU9VpGUoj+3WbUtgWJBlIq6XJgSLbEhtGxHjhMwWIn2PXzyj4Q61l+tUTtysnOceTA+1uUg6rtGDX89R1ywr6BjNe9Y40HMuZMEC5abkFtnh/9QUy8jE7lP0UTvV7/xK3G5WA3Aca4mWt2afkq9QFopioQ6yI65kWbZNeY1vcdv+SRAK8DVzb/WHpK8jkPOztaM+sTgjBEiNmbI12Um0w6vDZPjxk2sxDhWTeU3yehyOIzZ4BDYzWS2HBndp6ABEXj6J94jRa53dG/sEgZPOS8ebNCp/4f4jX1BtUB/loZvy4FlV4b8ZQZLvN9n/6F+UXR4ccrI+BOGfdjZGtOMym8O1qV4ea9ZxH4nWogCYqtICZpssm5WewU8ZRhvcfvAk7Wk19PmpZv/7Y9AQWCt9aCM6VGOtYnaRgeeuS8cMLRbBWwEE3+1shgmmH34FkcKnAbIrSzNLqe8JpH+fUudR3Hvj+Mi1fPAUNE6Ltxa/Lpz+DbCmSfaefFNLYYX3R5xrbM=
