version: '3'
services:
  server:
    env_file: server/.env.development
    restart: always
    build: .
    ports:
      - '8080:3001'
    volumes:
      - './client/build/images:/apps/medmcq/images'
